# Generated by Django 6.0.3 on 2026-05-12 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Material Icon name (e.g., 'self_improvement')", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/courses/categories/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True, help_text='Optional rich text content')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('page_type', models.CharField(choices=[('about', 'About Us'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy'), ('faq', 'FAQ'), ('contact', 'Contact Us'), ('custom', 'Custom Page')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/info/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info Page',
                'verbose_name_plural': 'Info Pages',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Youth K.E.Y Series', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pages/settings/')),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/home/banners/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, help_text="Optional: URL path like '/course/123/' or external link", max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('link_type', models.CharField(choices=[('course', 'Course'), ('category', 'Category'), ('external', 'External URL')], default='course', help_text='What happens when user taps this banner?', max_length=20)),
                ('category_slug', models.CharField(blank=True, help_text="Category slug for category links (e.g., 'personal-development')", max_length=100)),
                ('external_url', models.URLField(blank=True, help_text='Full URL for external links (e.g., https://youtube.com/...)')),
                ('linked_course', models.ForeignKey(blank=True, help_text='If set, tapping banner opens this course (overrides button_link)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_banners', to='courses.course')),
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banners',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeFeaturedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('label', models.CharField(blank=True, help_text="e.g. 'Top Pick', 'New', 'Bestseller'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_on_home', to='courses.course')),
            ],
            options={
                'verbose_name': 'Home Featured Course',
                'verbose_name_plural': 'Home Featured Courses',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Main Dashboard',
                'verbose_name_plural': '🏠  Main Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='PagesDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Pages Dashboard',
                'verbose_name_plural': '📋  Pages Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
    ]
