# Generated by Django 6.0.3 on 2026-05-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionProxy',
        ),
    ]
