# Generated by Django 6.0.3 on 2026-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_delete_sectionproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learning_points_text',
            field=models.TextField(blank=True, help_text='One learning point per line'),
        ),
    ]
