# Generated by Django 6.0.3 on 2026-06-03 01:20

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_learning_points_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='resource_link',
            field=models.URLField(blank=True, default='', help_text='Optional. Any URL you want students to visit — YouTube, TikTok, a PDF, a website, anything.'),
        ),
        migrations.AddField(
            model_name='module',
            name='resource_link_label',
            field=models.CharField(blank=True, default='', help_text='Button label shown to students, e.g. "Watch on YouTube" or "Download worksheet". Defaults to the URL if left blank.', max_length=120),
        ),
        migrations.AddField(
            model_name='module',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, WebM, MOV …). Leave blank if using an external URL.', null=True, upload_to=courses.models.module_video_path),
        ),
        migrations.AddField(
            model_name='module',
            name='video_type',
            field=models.CharField(choices=[('url', 'External URL'), ('upload', 'Uploaded File'), ('none', 'No Video')], default='none', help_text='Choose "Uploaded File" to upload a video from your device, or "External URL" to paste a link.', max_length=10),
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Paste a YouTube embed, Vimeo, or any direct video URL. Used only when Video Type is "External URL".'),
        ),
    ]
